services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: postgres
      DB_POSTGRESDB_HOST: aws-0-sa-east-1.pooler.supabase.com
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres.jbscmiacbxvsngdpnfhn
      DB_POSTGRESDB_SCHEMA: n8n
      DB_POSTGRESDB_PASSWORD: "*42Jr%1$1sAG%c%j"

volumes:
  n8n_data:
